### DISCUSSION TITLE
Best practices for using NACK with multi-tenant setup

### DISCUSSION THREAD

**Discussion by kejne** [nats-io/nack#252] [Q&A]
Using the `Account` (maybe better named `AccountConnectionDetails`?) jetstreams can be created for every account, but it quickly becomes a lot of credentials.

What I came up with, was to generate a user for every account which has the following credentials which NACK can use to assume a user for the account in scope:

```yaml
  permissions:
    pub:
      allow: 
        - $JS.API.STREAM.INFO.>
        - $JS.API.STREAM.CREATE.>
        - $JS.API.STREAM.UPDATE.>
        - $JS.API.CONSUMER.INFO.>
        - $JS.API.CONSUMER.CREATE.>
        - $JS.API.CONSUMER.UPDATE.>
        - $JS.API.CONSUMER.DELETE.>
        - $JS.API.CONSUMER.DURABLE.CREATE.>
        - $JS.API.INFO
    sub:
      allow: 
        - _INBOX.>
```

Does anyone have a better solution or pointers to what would otherwise be a good approach? In this case I would like to limit the permission as much as possible, but still be able to create a user automatically which would be able to manage the jetstream resources of the accounts used within the cluster.
