### ISSUE TITLE
Feature request: Add support for Jetstream domain

### ISSUE THREAD

**Issue by TarasLykhenko** [nats-io/nack#138]
### What motivated this proposal?

I am trying to implement Jetstream with leaf nodes following a spoke/hub architecture, but NACK currently does not support specifying the Jetstream domain in which the stream should be created. https://github.com/nats-io/jetstream-leaf-nodes-demo/tree/main

### What is the proposed change?

I am proposing to add a new field to the Stream and Consumer called `jsDomain` that overwrites the default jetstream domain.

```
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: mystream
spec:
  name: mystream
  subjects: ["orders.*"]
  jsDomain: "spoke-1"
  storage: memory
  maxAge: 1h
```

Moreover, to add the ability to set the default jsDomain that is used when no domain is specified in the CR.
