### ISSUE TITLE
Allow Authentication with ServiceAccount Token

### ISSUE THREAD

**Issue by martin31821** [nats-io/nack#239]
### What motivated this proposal?

With the new auth callout feature, I'd like to introduce the functionality to authenticate with the NACK's ServiceAccount if there's one present. 

The motivation behind this is to minimize manual setup and have the possibility to use already-established infrastructure components. 

### What is the proposed change?

I'd propose changing the account resource to not only allow referencing a secret but also load the token or the user from a file within the NACK countainer.

It could look like this:

```yaml
apiVersion: jetstream.nats.io/v1beta3
kind: Account
metadata:
  name: my-account
spec:
  user:
    name: nack-user
    passwordFile: /var/run/secrets/kubernetes.io/serviceaccount/token
```

### Who benefits from this change?

This change would benefit everyone who's running NATS on Kubernetes and uses Auth Callouts to utilize their Kubernetes Service Accounts to authenticate their services.

### What alternatives have you evaluated?

An alternative to this approach would be to ditch the service accounts and run an own X509 PKI with cert-manager and inline all of the authorizations.
