### ISSUE TITLE
Not possible to create an consumer with filterSubject containing wildcards and get the k8s resource into ready state

### ISSUE THREAD

**Issue by svallebro** [nats-io/nack#245]
### What version were you using?

0.17.1

### What environment was the server running in?

k8s linux x86

### Is this defect reproducible?

```yaml
# Source: nt-tems-ssv-services/templates/kpidataprocessorservice.yaml
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: broken-consumer-1
  namespace: default
spec:
  ackPolicy: explicit
  ackWait: 30s
  deliverPolicy: all
  durableName: broken-consumer-1
  filterSubject: 'some.*.*.more'
  maxAckPending: 35000
  maxDeliver: 1000
  streamName: Stream
---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: broken-consumer-2
  namespace: default
spec:
  ackPolicy: explicit
  ackWait: 30s
  deliverPolicy: all
  durableName: broken-consumer-2
  filterSubjects:
  - 'some.*.*.more'
  maxAckPending: 35000
  maxDeliver: 1000
  streamName: Stream
---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: working-consumer-1
  namespace: default
spec:
  ackPolicy: explicit
  ackWait: 30s
  deliverPolicy: all
  durableName: broken-consumer-1
  filterSubject: 'some.a.b.v1.more'
  maxAckPending: 35000
  maxDeliver: 1000
  streamName: Stream
---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: working-consumer-2
  namespace: default
spec:
  ackPolicy: explicit
  ackWait: 30s
  deliverPolicy: all
  durableName: test-consumer-
  filterSubjects:
  - 'some.*.*.v1.more'
  - 'some.*.*.v0.more'
  maxAckPending: 35000
  maxDeliver: 1000
  streamName: Stream
---
```

### Given the capability you are leveraging, describe your expectation?

kubectl get consumer 
NAME                                   STATE   STREAM    CONSUMER                          ACK POLICY
broken-consumer-1             Errored Stream      broken-consumer-1             explicit
broken-consumer-2             Errored Stream      broken-consumer-2             explicit
working-consumer-1           Ready   Stream       working-consumer-2           explicit
working-consumer-2           Ready   Stream       working-consumer-2           explicit

### Given the expectation, what is the defect you are observing?

kubectl get consumer 
NAME                                   STATE   STREAM    CONSUMER                          ACK POLICY
broken-consumer-1             Ready   Stream      broken-consumer-1             explicit
broken-consumer-2             Ready   Stream      broken-consumer-2             explicit
working-consumer-1           Ready   Stream       working-consumer-2           explicit
working-consumer-2           Ready   Stream       working-consumer-2           explicit

**Comment by kejne** [comment]
Got the same problem. NACK logs give this error:
```
E0522 12:17:15.479760       1 controller.go:347] "Reconciler error" err="create or update: create or update consumer: nats: connection closed" controller="consumer" controllerGroup="jetstream.nats.io" controllerKind="Consumer" Consumer="system-a-dev-euw1/h
ello-b" namespace="system-a-dev-euw1" name="hello-b" reconcileID="f17eae2c-77d7-4049-a1cf-194ac002ea83"
```

And when checking the NATS logs, it seems like the consumer is created - but NACK continues to try to update the consumer:
```
nats [7] 2025/05/22 12:56:19.069800 [INF] JetStream cluster new consumer leader for 'ABBPTJUUV43HKZITWCXBAQZEOOA43AKGA42ROZAR22YVDBDMKZHLD7AM > hello > helloa'
nats [7] 2025/05/22 13:00:18.425499 [INF] JetStream cluster new consumer leader for 'ABBPTJUUV43HKZITWCXBAQZEOOA43AKGA42ROZAR22YVDBDMKZHLD7AM > hello > helloa'
```

**Comment by Jarema** [comment]
Hey. thanks for the report.
We're looking into this.

**Comment by Jarema** [comment]
Could you provide `kubectl describe streams Stream` and `kubectl describe consumers broken-consumer-1`?

I cannot reproduce your issue.

Here is my example:


```
---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: stream
spec:
  name: stream
  subjects: ["test.>"]
  storage: file
  maxAge: 1h
---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: broken-consumer-1
  namespace: default
spec:
  ackPolicy: explicit
  ackWait: 30s
  deliverPolicy: all
  durableName: broken-consumer-1
  filterSubject: test.*.*.more
  maxAckPending: 35000
  maxDeliver: 1000
  streamName: stream
---
```
