### ISSUE TITLE
Feature request: add Bucket resource

### ISSUE THREAD

**Issue by cortopy** [nats-io/nack#75]
This is just a feature request for NACK to handle Key/Value buckets in addition to Consumer and Stream.

**Comment by Deimos2** [comment]
This should be a feature, but you can also create a k/v bucket from a Stream as mentioned in https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-8.md#buckets

**Comment by dwooldridge-ctoken** [comment]
Hi, it would be really nice to have a KV Bucket resource to work with. Do you think this is something that may be implemented?

**Comment by Jarema** [comment]
Yes. It is.
However, first we want to finish the rework of nack internals.

**Comment by praveenperera** [comment]
I set up some buckets using NACK following:  https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-8.md#buckets

But now I'm getting this warning: `configuration format and needs a configuration upgrade`

What should I change?

**Comment by dozsa** [comment]
Any update on when K/V bucket setup would be supported? +1 on the usefulness of such a feature. Thanks.

**Comment by SimonSchmid** [comment]
+1

**Comment by praveenperera** [comment]
Here is an example of how to create a bucket 

```yaml
---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: task-store
  namespace: nats
spec:
  name: KV_v1-task-store-borsh
  account: nack
  subjects: ["$KV.v1-task-store-borsh.>"]
  maxMsgsPerSubject: 1
  storage: file
  maxAge: 200h
  retention: limits
  duplicateWindow: 1m
  replicas: 3
```
