### ISSUE TITLE
Extend Nats auth to allow User Password option

### ISSUE THREAD

**Issue by anthonycorbacho** [nats-io/nack#76]
Hi,

I would like to know if it make sense to also allow passing User and Password as part of the auth option?
Currently only NKey file is allowed.

**Comment by hhk7734** [comment]
Try the below config

```yaml
jetstream:
  nats:
     url: nats://<user>:<password>@<domain>:<port>
```
