### ISSUE TITLE
error when deploying push consumer. consumer with flow control also needs heartbeats (10108)

### ISSUE THREAD

**Issue by treksler** [nats-io/nack#97]
following the README to do a test deploy

when deploying the push consumer
```
kubectl apply -f https://raw.githubusercontent.com/nats-io/nack/main/deploy/examples/consumer_push.yml
```
it ends up in an error state with 
```
failed to create consumer "my-push-consumer" on stream "mystream": consumer with flow control also needs heartbeats (10108)
```

i am new to nats and jetstream, so correct me if i am way off here, but should the push consumer example be updated to something like

```
---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: my-push-consumer
spec:
  streamName: mystream
  durableName: my-push-consumer
  deliverSubject: my-push-consumer.orders
  deliverPolicy: last
  ackPolicy: none
  replayPolicy: instant
  description: my consumer description
  flowControl: true
  heartbeatInterval: 1s
```
